In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
import tkinter as tk
from tkinter import ttk
from warnings import filterwarnings




In [2]:
filterwarnings(action='ignore')

data = pd.read_csv("winequality-red.csv")
print("Successfully Imported Data!")

Successfully Imported Data!


In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['quality'] = le.fit_transform(data['quality'])

X = data.drop('quality', axis=1)
y = data['quality']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [5]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)


RandomForestClassifier()

In [6]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

# Display confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

Accuracy: 0.653125
Confusion Matrix:
[[ 0  0  1  0  0  0]
 [ 0  0  6  4  0  0]
 [ 0  0 99 31  0  0]
 [ 0  0 32 90 10  0]
 [ 0  0  0 21 20  1]
 [ 0  0  0  0  5  0]]


In [8]:
def predict_wine_quality(fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol):
    input_data = np.array([fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol]).reshape(1, -1)
    prediction = model.predict(input_data)[0]
    return int(prediction)

In [9]:
root = tk.Tk()
root.title("Wine Quality Prediction")

# Create input fields
input_fields = [
    ("Fixed Acidity", 0.0, 15.0),
    ("Volatile Acidity", 0.0, 1.5),
    ("Citric Acid", 0.0, 1.0),
    ("Residual Sugar", 0.0, 15.0),
    ("Chlorides", 0.0, 0.6),
    ("Free Sulfur Dioxide", 0.0, 100.0),
    ("Total Sulfur Dioxide", 0.0, 300.0),
    ("Density", 0.9, 1.0),
    ("pH", 2.0, 4.0),
    ("Sulphates", 0.0, 2.0),
    ("Alcohol", 8.0, 15.0)
]

input_values = {}
for field in input_fields:
    label, min_value, max_value = field
    row = tk.Frame(root)
    row.pack(fill="x", padx=5, pady=5)
    tk.Label(row, text=label, width=20).pack(side="left")
    entry = tk.Entry(row)
    entry.insert(0, str((min_value + max_value) / 2))
    entry.pack(side="left", fill="x", expand=True)
    input_values[label] = entry

def predict_button_click():
    input_data = [float(input_values[label].get()) for label, _, _ in input_fields]
    quality = predict_wine_quality(*input_data)
    result_label.config(text=f"Predicted Wine Quality: {quality}")

    # Check for qualities higher than 5
    if quality > 5:
        print(f"Input values that produce quality higher than 5: {input_data}")

predict_button = tk.Button(root, text="Predict", command=predict_button_click)
predict_button.pack(pady=10)

result_label = tk.Label(root, text="")
result_label.pack()

root.mainloop()
